# Generated by Django 3.1.2 on 2020-10-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('debut_year', models.DateField()),
                ('num_stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('songs', models.CharField(max_length=500)),
                ('year', models.DateField()),
                ('filetype', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('collection', models.CharField(max_length=50)),
                ('num_stars', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_treasure_trove.musician')),
            ],
        ),
    ]
